batch_size: 10000
datasync_jar: "DataSync-1.7.2.jar"
odn:
  username:  <%= ENV["ODN_USERNAME"] %>
  password:  <%= ENV["ODN_PASSWORD"] %>
  app_token: <%= ENV["ODN_APP_TOKEN"] %>
  ignore_ssl: true
  domain:    odn.data.socrata.com
  status_dataset: bnca-7rbq

github:
  access_token: <%= ENV['GITHUB_ACCESS_TOKEN'] %>
  repo: open-data-network/schema-mappings

datasets:
  ki4q-6ek7: microschemas/points_of_interest

supertrooper:
  domain: odn.data.socrata.com
  username:  <%= ENV["ODN_USERNAME"] %>
  password:  <%= ENV["ODN_PASSWORD"] %>
  app_token: <%= ENV["ODN_APP_TOKEN"] %>
  agencies: https://moto.data.socrata.com/resource/fax2-dw8p
  # agency_filter: "state IN ('MD', 'VA', 'DC') AND account_type != 'Missing'"
  agency_filter: "account_type != 'Missing'"
  gazeteer: https://odn.data.socrata.com/resource/gm3u-gw57
  places: https://odn.data.socrata.com/resource/h7w8-g2pa
  places_db: regions/places.sqlite
  # ym_dest_uid: yq6p-fzyt
  # y_dest_uid: drhh-dey3
  max_geom_length: 4000
  simplify: 0.001

macklin:
  stop_words:
    - "^Village\\s+of\\s+"
    - ",\\s+.*\\s+County"
    - "\\s+Township,\\s+.*\\s+County"
    - "\\s+Town(ship)?$"
    - "(Town\\s+and\\s+)?Village$"
    - "\\s+Borough$"
    - "\\s+City$"
    - ",$"
  files:
    2014: https://ucr.fbi.gov/crime-in-the-u.s/2014/crime-in-the-u.s.-2014/tables/table-8/Table_8_Offenses_Known_to_Law_Enforcement_by_State_by_City_2014.xls
    2013: https://ucr.fbi.gov/crime-in-the-u.s/2013/crime-in-the-u.s.-2013/tables/table-8/table_8_offenses_known_to_law_enforcement_by_state_by_city_2013.xls
    2012: https://ucr.fbi.gov/crime-in-the-u.s/2012/crime-in-the-u.s.-2012/tables/8tabledatadecpdf/table_8_offenses_known_to_law_enforcement_by_state_by_city_2012.xls
    2011: https://ucr.fbi.gov/crime-in-the-u.s/2011/crime-in-the-u.s.-2011/tables/table_8_offenses_known_to_law_enforcement_by_state_by_city_2011.xls
    2010: https://ucr.fbi.gov/crime-in-the-u.s/2010/crime-in-the-u.s.-2010/tables/10tbl08.xls
    2009: https://www2.fbi.gov/ucr/cius2009/data/documents/09tbl08.xls
    2008: https://www2.fbi.gov/ucr/cius2008/data/documents/08tbl08.xls
    2007: https://www2.fbi.gov/ucr/cius2007/data/documents/07tbl08.xls
    2006: https://www2.fbi.gov/ucr/cius2006/data/documents/06tbl08.xls
    # In 2005 they changed the format of "Table 8" so we'll need to use a different technique
  timeout: 360
  domain: odn.data.socrata.com
  username:  <%= ENV["ODN_USERNAME"] %>
  password:  <%= ENV["ODN_PASSWORD"] %>
  app_token: <%= ENV["ODN_APP_TOKEN"] %>
  roster: https://odn.data.socrata.com/resource/kksg-4m3m
  states: https://odn.data.socrata.com/resource/9qwh-uq8v
  # dest_uid: 8x3g-rxtx

mcdreamy:
  files:
    2014: http://www.census.gov/did/www/sahie/data/files/sahie_2014.csv.zip
    2013: http://www.census.gov/did/www/sahie/data/files/sahie_2013.csv.zip
    2012: http://www.census.gov/did/www/sahie/data/files/sahie_2012.csv.zip
    2011: http://www.census.gov/did/www/sahie/data/files/sahie_2011.csv.zip
    2010: http://www.census.gov/did/www/sahie/data/files/sahie_2010.csv.zip
    2009: http://www.census.gov/did/www/sahie/data/files/sahie_2009.csv.zip
    2008: http://www.census.gov/did/www/sahie/data/files/sahie_2008.csv.zip

  skip_lines: 79

  var_columns:
    - NIPR
    - NUI
    - PCTUI
    - PCTIC
    - PCTELIG
    - PCTLIIC

  mappings:
    geocat:
      40: state
      50: county

    agecat:
      0: Under 65
      1: 18 to 64
      2: 40 to 64
      3: 50 to 64
      4: Under 19
      5: 21 to 64

    racecat:
      0: All races
      1: White alone, not Hispanic
      2: Black alone, not Hispanic
      3: Hispanic, any race

    sexcat:
      0: Both sexes
      1: Male
      2: Female

    iprcat:
      0: All income levels
      1: At or below 200% of poverty
      2: At or below 250% of poverty
      3: At or below 138% of poverty
      4: At or below 400% of poverty
      5: Between 138% and 400% of poverty
