batch_size: 10000
odn:
  username:  <%= ENV["ODN_USERNAME"] %>
  password:  <%= ENV["ODN_PASSWORD"] %>
  app_token: <%= ENV["ODN_APP_TOKEN"] %>
  ignore_ssl: true
  domain:    odn.data.socrata.com
  status_dataset: bnca-7rbq

github:
  access_token: <%= ENV['GITHUB_ACCESS_TOKEN'] %>
  repo: open-data-network/schema-mappings

datasets:
  ki4q-6ek7: microschemas/points_of_interest

supertrooper:
  domain: odn.data.socrata.com
  username:  <%= ENV["ODN_USERNAME"] %>
  password:  <%= ENV["ODN_PASSWORD"] %>
  app_token: <%= ENV["ODN_APP_TOKEN"] %>
  agencies: https://moto.data.socrata.com/resource/fax2-dw8p
  # agency_filter: "state IN ('MD', 'VA', 'DC') AND account_type != 'Missing'"
  agency_filter: "account_type != 'Missing'"
  gazeteer: https://odn.data.socrata.com/resource/gm3u-gw57
  places: https://odn.data.socrata.com/resource/h7w8-g2pa
  places_db: regions/places.sqlite
  # ym_dest_uid: yq6p-fzyt
  # y_dest_uid: drhh-dey3
  max_geom_length: 4000
  simplify: 0.001

macklin:
  templates:
    2014: https://www.fbi.gov/about-us/cjis/ucr/crime-in-the-u.s/2014/crime-in-the-u.s.-2014/tables/table-8/table-8-by-state/Table_8_Offenses_Known_to_Law_Enforcement_by_{{ state_scored }}_by_City_2014.xls/output.xls
    2013: https://www.fbi.gov/about-us/cjis/ucr/crime-in-the-u.s/2013/crime-in-the-u.s.-2013/tables/table-8/table-8-state-cuts/table_8_offenses_known_to_law_enforcement_{{ state_scored_downcase }}_by_city_2013.xls/output.xls
    2012: https://www.fbi.gov/about-us/cjis/ucr/crime-in-the-u.s/2012/crime-in-the-u.s.-2012/tables/8tabledatadecpdf/table-8-state-cuts/table_8_offenses_known_to_law_enforcement_by_{{ state_scored_downcase }}_by_city_2012.xls/output.xls
    2011: https://www.fbi.gov/about-us/cjis/ucr/crime-in-the-u.s/2011/crime-in-the-u.s.-2011/tables/table8statecuts/table_8_offenses_known_to_law_enforcement_{{ state_scored_downcase }}_by_city_2011.xls/output.xls
    2010: https://www.fbi.gov/about-us/cjis/ucr/crime-in-the-u.s/2010/crime-in-the-u.s.-2010/tables/table-8/10tbl08{{ state_abbr_downcase }}.xls/output.xls
    2009: https://www2.fbi.gov/ucr/cius2009/data/documents/09tbl08{{ state_abbr_downcase }}.xls
    2008: https://www2.fbi.gov/ucr/cius2008/data/documents/08tbl08{{ state_abbr_downcase }}.xls
    2007: https://www2.fbi.gov/ucr/cius2007/data/documents/07tbl08{{ state_abbr_downcase }}.xls
    2006: https://www2.fbi.gov/ucr/cius2006/data/documents/06tbl08{{ state_abbr_downcase }}.xls
    # In 2005 they changed the format of "Table 8" so we'll need to use a different technique
  timeout: 360
  domain: odn.data.socrata.com
  username:  <%= ENV["ODN_USERNAME"] %>
  password:  <%= ENV["ODN_PASSWORD"] %>
  app_token: <%= ENV["ODN_APP_TOKEN"] %>
  roster: https://odn.data.socrata.com/resource/7g2b-8brv
  states: https://odn.data.socrata.com/resource/9qwh-uq8v
  dest_uid: 8x3g-rxtx
