source 'https://rubygems.org'

ruby '2.3.0'

gem 'thor'
gem 'soda-ruby', '~> 0.2.19'
gem 'activesupport'
gem 'httparty'
gem 'octokit', '~> 4.0'
gem 'sqlite3'#, :source => 'https://VHjmFTmfzmcLxjnF69Fe@repo.fury.io/chrismetcalf/'
gem 'parallel'
gem 'ruby-progressbar'
gem 'roo'
gem 'roo-xls'
gem 'rubyzip'
